# --- !Ups
CREATE TABLE  PAINTERS
(
  PAINTER_ID NUMBER(10) NOT NULL,
  FIRST_NAME VARCHAR2(255) NOT NULL,
  LAST_NAME VARCHAR2(255) NOT NULL,
  PSEUDONYM VARCHAR2(255) NOT NULL,
  BIRTH_DATE DATE ,
  DATE_OF_DEATH DATE,
  PICTURE VARCHAR2(4096)
);
CREATE UNIQUE INDEX PK_PAINTERS_ID ON PAINTERS(PAINTER_ID);
--If a painter clashes on all of these, we will treat them as the same person.
CREATE UNIQUE INDEX UK_PAINTERS_DETAILS ON PAINTERS(FIRST_NAME, LAST_NAME, PSEUDONYM);

CREATE SEQUENCE SEQ_SLN_PAINTERS
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 10
    INCREMENT BY 1;

INSERT INTO PAINTERS values  (1, 'Vincent', 'van Gogh', 'VVG', NULL, NULL, 'https://upload.wikimedia.org/wikipedia/commons/d/df/Van_Gogh_self_portrait_as_an_artist.jpg');
INSERT INTO PAINTERS values  (2, 'San', 'of Africa', 'Pre-historic San People', NULL, NULL, 'https://en.wikipedia.org/wiki/San_people#/media/File:Namibian_Bushmen_Girls.JPG');

CREATE TABLE PAINTINGS
(
  PAINTING_ID NUMBER(15) NOT NULL,
  PAINTING_NAME VARCHAR2(255),
  PAINTER_ID NUMBER(10), -- FOR UNKNOWN ARTISTS
  YEAR_FINISHED NUMBER(4) NOT NULL,
  SURFACE_TYPE NUMBER(4) NOT NULL,
  MEDIUM_TYPE NUMBER (4) NOT NULL,
  URL VARCHAR2(255)
);

CREATE UNIQUE INDEX PK_PAINTINGS_ID ON PAINTINGS(PAINTING_ID);


# --- !Downs
DROP TABLE PAINTERS;
DROP TABLE PAINTINGS;
