# ---Ups!
CREATE TABLE PAINETERS
(
  PAINTER_ID NUMBER(10) NOT NULL,
  FIRST_NAME VARCHAR2(255) NOT NULL,
  LAST_NAME VARCHAR2(255) NOT NULL,
  PSEUDONYM VARCHAR2(255) NOT NULL,
  BIRTH_DATE DATE ,
  DATE_OF_DEATH DATE
);
CREATE UNIQUE INDEX PK_PAINTERS_ID ON PAINETERS(PAINTER_ID);
--If a painter clashes on all of these, we will treat them as the same person.
CREATE UNIQUE INDEX UK_PAINTERS_DETAILS ON PAINETERS(FIRST_NAME, LAST_NAME, PSEUDO_NAME);

CREATE SEQUENCE SEQ_SLN_PAINTERS
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 10
    INCREMENT BY 1;


CREATE TABLE PAINTINGS
(
  PAINTING_ID NUMBER(15) NOT NULL,
  PAINTING_NAME VARCHAR2(255),
  PAINTER_ID NUMBER(10), -- FOR UNKNOWN ARTISTS
  YEAR_FINISHED NUMBER(4) NOT NULL,
  SURFACE_TYPE NUMBER(4) NOT NULL,
  MEDIUM_TYPE NUMBER (4) NOT NULL,
  URL VARCHAR2(255)

);
CREATE UNIQUE INDEX PK_PAINTINGS_ID ON PAINTINGS(PAINTING_ID);
# ---Downs!
